# Generated by Django 5.1.5 on 2025-02-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_address_country_remove_address_is_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='full_name',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='00000', max_length=20),
        ),
    ]
